services:
  api:
    container_name: mycoworking-api
    image: maven:3.9.9-eclipse-temurin-17
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: -XX:+UseZGC
    volumes:
      - .:/app
      - ${HOME}/.m2:/root/.m2
    ports:
      - "8080:8080"
    working_dir: /app
    command: mvn spring-boot:run
    depends_on:
      - db

  db:
    container_name: mycoworking-db
    image: postgres
    environment:
      - POSTGRES_DB=mycoworking
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
