services:
  api:
    image: maven:3.9.9-eclipse-temurin-17
    container_name: mycoworking-api
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: -XX:+UseZGC
    volumes:
      - .:/app
      - ${HOME}/.m2:/root/.m2
    ports:
      - "8080:8080"
    working_dir: /app
    command: mvn spring-boot:run
    depends_on:
      - mariadb
    mem_limit: 1g
    cpus: 0.5
    restart: on-failure

  mariadb:
    image: mariadb
    container_name: mycoworking-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mycoworking
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    mem_limit: 256m
    cpus: 0.5
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
